# Generated by Django 3.1 on 2020-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacerentals', '0002_pg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='address',
            field=models.CharField(default='yet to be known', max_length=100),
        ),
    ]
