# Generated by Django 3.1 on 2020-08-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacerentals', '0003_pg_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(default='Student', max_length=13),
        ),
    ]
